In [1]:
#Question 1:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
#Question 2:
import numpy as np
a1=[] 
a2=[]

print("Elements List 1:")
for i in range(0, 5):
    ele = int(input())
    a1.append(ele)
print("Elements List 2:")
for i in range(0, 5):
    ele = int(input())
    a2.append(ele) 
print(a1,type(a1))
print(a2,type(a2))
a1 = np.array(a1)
a2 = np.array(a2)
print(a1,type(a1))
print(a2,type(a2))
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

Elements List 1:
2
4
5
6
7
Elements List 2:
9
10
11
4
5
[2, 4, 5, 6, 7] <class 'list'>
[9, 10, 11, 4, 5] <class 'list'>
[2 4 5 6 7] <class 'numpy.ndarray'>
[ 9 10 11  4  5] <class 'numpy.ndarray'>
[ 2  4  5  6  7  9 10 11  4  5]
[ 2  4  4  5  5  6  7  9 10 11]


In [7]:
#Question 3
import numpy as np
arr=np.array([[1,2],[2,4],[5,7]])
print("Size of Array: ",arr.size)
print("Dimension of Array: ",arr.ndim)

Size of Array:  6
Dimension of Array:  2


In [10]:
#Question 4:
import numpy as np
arr=np.arange(12)
arr1=arr[np.newaxis,:]
arr2=arr[:,np.newaxis]
print(arr1)
print(arr2)
arr1=np.expand_dims(arr, axis = 0) 
arr2=np.expand_dims(arr, axis = 1) 
print(arr1)
print(arr2)


[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [11]:
#Question 5:
import numpy as np
a=np.arange(9).reshape(3,3)
b=np.ones(9).reshape(3,3)
c=np.vstack((a,b))
print("Vertically stacked: \n",c)
d=np.hstack((a,b))
print("Horizontally stacked: \n",d)

Vertically stacked: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Horizontally stacked: 
 [[0. 1. 2. 1. 1. 1.]
 [3. 4. 5. 1. 1. 1.]
 [6. 7. 8. 1. 1. 1.]]


In [12]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3], dtype=int64))
